theme = "hugo-ink"

# Override these settings with your own
title = "zathura"
baseURL = "https://zathura.xyz/"
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true

[languages]
    [languages.pt]
        languageName = "Português"
        contentDir = "content/pt"

        # Controls the navigation
        [[languages.pt.menu.main]]
          identifier = "home"
          name = "início"
          title = "Início"
          url = "/pt/"

        [[languages.pt.menu.main]]
          identifier = "poesia"
          name = "poesia"
          title = "Poesia"
          url = "/pt/poetry"

    [languages.en]
        languageName = "English"
        contentDir = "content/en"

        # Controls the navigation
        [[languages.en.menu.main]]
          identifier = "home"
          name = "home"
          title = "Home"
          url = "/en/"

# Optional params
[params]
  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/gpontesss"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://zathura.xyz/index.xml"

[[params.social]]
name = "YouTube"
icon = "youtube"
url = "https://www.youtube.com/channel/UCVMs7M4YAPA1hNEKLVnpvwA"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/gpontesss"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/gpontesss"

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true
