# theme = "hugo-ink"
theme = "rework"

# Override these settings with your own
title = "vertical ascension"
baseURL = "https://gpontesss.xyz/"
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true
pagination = 10

[languages]
    [languages.pt]
        languageName = "Português"
        contentDir = "content/pt"

        [languages.pt.params]
          subtitle = "A jornada da vida, através da minha perspectiva"

        # ------------
        # social links
        # ------------
        [[languages.pt.params.social]]
          name = "RSS"
          icon = "rss"
          url = "https://zathura.xyz/pt/index.xml"

        [[languages.pt.params.social]]
          name = "Github"
          icon = "github"
          url = "https://github.com/gpontesss"

        [[languages.pt.params.social]]
          name = "LinkedIn"
          icon = "linkedin"
          url = "https://www.linkedin.com/in/gpontesss"

        # [[languages.pt.params.social]]
        # name = "YouTube"
        # icon = "youtube"
        # url = "https://www.youtube.com/channel/UCVMs7M4YAPA1hNEKLVnpvwA"

        # [[languages.pt.params.social]]
        # name = "Instagram"
        # icon = "instagram"
        # url = "https://instagram.com/gpontesss"

        # ------------
        # header links
        # ------------
        [[languages.pt.menu.main]]
          identifier = "home"
          name = "tudo"
          title = "Tudo"
          url = "/pt/"
          weight = 1

        [[languages.pt.menu.main]]
          identifier = "about"
          name = "sobre"
          title = "Sobre"
          url = "/pt/about/"
          weight = 2

        [[languages.pt.menu.main]]
          identifier = "tags"
          name = "tags"
          title = "Tags"
          url = "/pt/tags/"
          weight = 3

    [languages.en]
        languageName = "English"
        contentDir = "content/en"

        [languages.en.params]
          subtitle = "Life's journey, through my perspective"

        # ------------
        # social links
        # ------------
        [[languages.en.params.social]]
          name = "RSS"
          icon = "rss"
          url = "https://zathura.xyz/en/index.xml"

        [[languages.en.params.social]]
          name = "Github"
          icon = "github"
          url = "https://github.com/gpontesss"

        [[languages.en.params.social]]
          name = "LinkedIn"
          icon = "linkedin"
          url = "https://www.linkedin.com/in/gpontesss"

        # [[languages.pt.params.social]]
        # name = "YouTube"
        # icon = "youtube"
        # url = "https://www.youtube.com/channel/UCVMs7M4YAPA1hNEKLVnpvwA"

        # [[languages.pt.params.social]]
        # name = "Instagram"
        # icon = "instagram"
        # url = "https://instagram.com/gpontesss"

        # ------------
        # header links
        # ------------
        [[languages.en.menu.main]]
          identifier = "home"
          name = "all"
          title = "All"
          url = "/en/"
          weight = 1

        [[languages.en.menu.main]]
          identifier = "about"
          name = "about"
          title = "About"
          url = "/en/about/"
          weight = 2

        [[languages.en.menu.main]]
          identifier = "tags"
          name = "tags"
          title = "Tags"
          url = "/en/tags/"
          weight = 3

# Optional params
[params]
  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

  avatar = "/svg/lion.svg"

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
